# Generated by Django 4.0.3 on 2023-10-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointmenet',
            new_name='Appointment',
        ),
    ]
