# Generated by Django 4.2.5 on 2023-10-24 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service_rest", "0002_rename_appointmenet_appointment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="Appointment_date",
            new_name="appointment_date",
        ),
    ]
